dbfilename redis_queue.rdb
dir /home/srikar/Desktop/shift_management_system/frappe-bench/config/pids
pidfile /home/srikar/Desktop/shift_management_system/frappe-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/srikar/Desktop/shift_management_system/frappe-bench/config/redis_queue.acl
